"""
exportProcedures.py
--------------------
SOURCE: Microsoft SQL Server (Loop-Loc_v1)
TARGET: create_procedures.sql  (output file)

NOTE: This script connects to SQL SERVER, not SQL Anywhere.
      Run this AFTER all stored procedures have been converted to T-SQL
      and created in SQL Server (end of Phase 6).

PURPOSE:
      Exports all user-created stored procedures from SQL Server into a
      single deployable SQL file: create_procedures.sql

      Use create_procedures.sql at go-live to deploy the completed
      T-SQL procedures to the production SQL Server instance.

Each procedure is written as:
  DROP PROCEDURE IF EXISTS [dbo].[proc_name];
  GO
  CREATE OR ALTER PROCEDURE [dbo].[proc_name] ...
  GO
"""

import re
import pyodbc

dst = pyodbc.connect(
    'DRIVER={ODBC Driver 17 for SQL Server};'
    'SERVER=LOOP-SQL2025;'
    'DATABASE=Loop-Loc_v1;'
    'Trusted_Connection=yes;'
)

def get_procedures(conn):
    cur = conn.cursor()
    cur.execute("""
        SELECT
            o.name,
            m.definition
        FROM sys.sql_modules m
        JOIN sys.objects o ON m.object_id = o.object_id
        WHERE o.type = 'P'
          AND o.is_ms_shipped = 0
        ORDER BY o.name
    """)
    return cur.fetchall()

procedures = get_procedures(dst)
dst.close()

print(f"Found {len(procedures)} procedure(s). Writing export file...\n")

with open('create_procedures.sql', 'w', encoding='utf-8') as f:
    f.write("-- =============================================================\n")
    f.write("-- SQL Server stored procedure export\n")
    f.write("-- Source database : Loop-Loc_v1 on LOOP-SQL2025\n")
    f.write("-- Generated by    : exportProcedures.py\n")
    f.write("--\n")
    f.write("-- Run this file in SSMS against the target database to deploy\n")
    f.write("-- all stored procedures.\n")
    f.write("-- =============================================================\n\n")

    for proc_name, definition in procedures:
        f.write(f"-- {'='*60}\n")
        f.write(f"-- PROCEDURE: {proc_name}\n")
        f.write(f"-- {'='*60}\n")

        # Drop first so the script is safe to re-run
        f.write(f"DROP PROCEDURE IF EXISTS [dbo].[{proc_name}];\n")
        f.write("GO\n\n")

        # sys.sql_modules stores the original CREATE PROCEDURE text.
        # Rewrite as CREATE OR ALTER so re-running is safe even if DROP is skipped.
        deploy_defn = re.sub(
            r'^CREATE\s+PROCEDURE\b',
            'CREATE OR ALTER PROCEDURE',
            definition,
            count=1,
            flags=re.IGNORECASE
        )

        f.write(deploy_defn)
        f.write("\nGO\n\n")
        print(f"  {proc_name}")

print(f"\nDone. {len(procedures)} procedure(s) written to create_procedures.sql")
