"""
exportTriggers.py
------------------
SOURCE: Microsoft SQL Server (Loop-Loc_v1)
TARGET: create_triggers.sql  (output file)

NOTE: This script connects to SQL SERVER, not SQL Anywhere.
      Run this AFTER all triggers have been converted to T-SQL
      and created in SQL Server (end of Phase 6).

PURPOSE:
      Exports all user-created triggers from SQL Server into a single
      deployable SQL file: create_triggers.sql

      Use create_triggers.sql at go-live to deploy the completed
      T-SQL triggers to the production SQL Server instance.

Each trigger is written as:
  DROP TRIGGER IF EXISTS [dbo].[trigger_name];
  GO
  CREATE OR ALTER TRIGGER [trigger_name] ON [dbo].[table_name] ...
  GO
"""

import re
import pyodbc

dst = pyodbc.connect(
    'DRIVER={ODBC Driver 17 for SQL Server};'
    'SERVER=LOOP-SQL2025;'
    'DATABASE=Loop-Loc_v1;'
    'Trusted_Connection=yes;'
)

def get_triggers(conn):
    cur = conn.cursor()
    cur.execute("""
        SELECT
            tr.name,
            tab.name  AS table_name,
            m.definition
        FROM sys.triggers tr
        JOIN sys.sql_modules m   ON tr.object_id  = m.object_id
        JOIN sys.tables tab      ON tr.parent_id  = tab.object_id
        WHERE tr.is_ms_shipped = 0
        ORDER BY tab.name, tr.name
    """)
    return cur.fetchall()

triggers = get_triggers(dst)
dst.close()

print(f"Found {len(triggers)} trigger(s). Writing export file...\n")

with open('create_triggers.sql', 'w', encoding='utf-8') as f:
    f.write("-- =============================================================\n")
    f.write("-- SQL Server trigger export\n")
    f.write("-- Source database : Loop-Loc_v1 on LOOP-SQL2025\n")
    f.write("-- Generated by    : exportTriggers.py\n")
    f.write("--\n")
    f.write("-- Run this file in SSMS against the target database to deploy\n")
    f.write("-- all triggers.\n")
    f.write("-- =============================================================\n\n")

    for trigger_name, table_name, definition in triggers:
        f.write(f"-- {'='*60}\n")
        f.write(f"-- TRIGGER : {trigger_name}\n")
        f.write(f"-- TABLE   : {table_name}\n")
        f.write(f"-- {'='*60}\n")

        # Drop first so the script is safe to re-run
        f.write(f"DROP TRIGGER IF EXISTS [dbo].[{trigger_name}];\n")
        f.write("GO\n\n")

        # Rewrite as CREATE OR ALTER so re-running is safe even if DROP is skipped
        deploy_defn = re.sub(
            r'^CREATE\s+TRIGGER\b',
            'CREATE OR ALTER TRIGGER',
            definition,
            count=1,
            flags=re.IGNORECASE
        )

        f.write(deploy_defn)
        f.write("\nGO\n\n")
        print(f"  {trigger_name:<45} {table_name}")

print(f"\nDone. {len(triggers)} trigger(s) written to create_triggers.sql")
